import { Employee, Department, Role, EmployeeStatus, ContractType } from '../types';

export const mockDepartments: Department[] = [
  {
    id: 'dept_1',
    name: 'Engineering',
    description: 'Software development and technical operations',
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'dept_2',
    name: 'Human Resources',
    description: 'Employee relations and organizational development',
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'dept_3',
    name: 'Marketing',
    description: 'Brand management and customer acquisition',
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'dept_4',
    name: 'Sales',
    description: 'Revenue generation and client relationships',
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'dept_5',
    name: 'Finance',
    description: 'Financial planning and accounting',
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
];

export const mockRoles: Role[] = [
  {
    id: 'role_1',
    title: 'Software Engineer',
    description: 'Develops and maintains software applications',
    level: 3,
    departmentId: 'dept_1',
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'role_2',
    title: 'Senior Software Engineer',
    description: 'Leads technical projects and mentors junior developers',
    level: 4,
    departmentId: 'dept_1',
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'role_3',
    title: 'Engineering Manager',
    description: 'Manages engineering teams and technical strategy',
    level: 5,
    departmentId: 'dept_1',
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'role_4',
    title: 'HR Specialist',
    description: 'Handles recruitment and employee relations',
    level: 3,
    departmentId: 'dept_2',
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'role_5',
    title: 'HR Manager',
    description: 'Oversees HR operations and policies',
    level: 4,
    departmentId: 'dept_2',
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'role_6',
    title: 'Marketing Specialist',
    description: 'Creates and executes marketing campaigns',
    level: 3,
    departmentId: 'dept_3',
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'role_7',
    title: 'Sales Representative',
    description: 'Manages client relationships and sales processes',
    level: 3,
    departmentId: 'dept_4',
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'role_8',
    title: 'Financial Analyst',
    description: 'Analyzes financial data and creates reports',
    level: 3,
    departmentId: 'dept_5',
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
];

export const mockEmployees: Employee[] = [
  {
    id: 'emp_1',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@company.com',
    phone: '+1-555-0101',
    hireDate: new Date('2023-03-15'),
    departmentId: 'dept_1',
    roleId: 'role_2',
    status: 'active' as EmployeeStatus,
    contractType: 'permanent' as ContractType,
    emergencyContact: {
      name: 'Jane Doe',
      relationship: 'Spouse',
      phone: '+1-555-0102',
      email: 'jane.doe@email.com',
    },
    createdAt: new Date('2023-03-15'),
    updatedAt: new Date('2023-03-15'),
  },
  {
    id: 'emp_2',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.johnson@company.com',
    phone: '+1-555-0201',
    hireDate: new Date('2023-06-01'),
    departmentId: 'dept_2',
    roleId: 'role_5',
    status: 'active' as EmployeeStatus,
    contractType: 'permanent' as ContractType,
    emergencyContact: {
      name: 'Michael Johnson',
      relationship: 'Spouse',
      phone: '+1-555-0202',
    },
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2023-06-01'),
  },
  {
    id: 'emp_3',
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'michael.chen@company.com',
    phone: '+1-555-0301',
    hireDate: new Date('2024-01-15'),
    departmentId: 'dept_1',
    roleId: 'role_1',
    status: 'active' as EmployeeStatus,
    contractType: 'permanent' as ContractType,
    probationEndDate: new Date('2024-07-15'),
    emergencyContact: {
      name: 'Lisa Chen',
      relationship: 'Mother',
      phone: '+1-555-0302',
    },
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'emp_4',
    firstName: 'Emily',
    lastName: 'Rodriguez',
    email: 'emily.rodriguez@company.com',
    phone: '+1-555-0401',
    hireDate: new Date('2023-09-20'),
    departmentId: 'dept_3',
    roleId: 'role_6',
    status: 'active' as EmployeeStatus,
    contractType: 'contract' as ContractType,
    emergencyContact: {
      name: 'Carlos Rodriguez',
      relationship: 'Father',
      phone: '+1-555-0402',
    },
    createdAt: new Date('2023-09-20'),
    updatedAt: new Date('2023-09-20'),
  },
  {
    id: 'emp_5',
    firstName: 'David',
    lastName: 'Wilson',
    email: 'david.wilson@company.com',
    phone: '+1-555-0501',
    hireDate: new Date('2024-11-01'),
    departmentId: 'dept_4',
    roleId: 'role_7',
    status: 'active' as EmployeeStatus,
    contractType: 'intern' as ContractType,
    probationEndDate: new Date('2025-05-01'),
    emergencyContact: {
      name: 'Mary Wilson',
      relationship: 'Mother',
      phone: '+1-555-0502',
    },
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2024-11-01'),
  },
  {
    id: 'emp_6',
    firstName: 'Jessica',
    lastName: 'Brown',
    email: 'jessica.brown@company.com',
    phone: '+1-555-0601',
    hireDate: new Date('2022-08-10'),
    departmentId: 'dept_5',
    roleId: 'role_8',
    status: 'on-leave' as EmployeeStatus,
    contractType: 'permanent' as ContractType,
    emergencyContact: {
      name: 'Robert Brown',
      relationship: 'Spouse',
      phone: '+1-555-0602',
    },
    createdAt: new Date('2022-08-10'),
    updatedAt: new Date('2022-08-10'),
  },
  {
    id: 'emp_7',
    firstName: 'Alex',
    lastName: 'Taylor',
    email: 'alex.taylor@company.com',
    phone: '+1-555-0701',
    hireDate: new Date('2023-12-01'),
    departmentId: 'dept_1',
    roleId: 'role_3',
    supervisorId: 'emp_1',
    status: 'active' as EmployeeStatus,
    contractType: 'permanent' as ContractType,
    emergencyContact: {
      name: 'Sam Taylor',
      relationship: 'Sibling',
      phone: '+1-555-0702',
    },
    createdAt: new Date('2023-12-01'),
    updatedAt: new Date('2023-12-01'),
  },
  {
    id: 'emp_8',
    firstName: 'Maria',
    lastName: 'Garcia',
    email: 'maria.garcia@company.com',
    phone: '+1-555-0801',
    hireDate: new Date('2024-12-15'),
    departmentId: 'dept_2',
    roleId: 'role_4',
    status: 'active' as EmployeeStatus,
    contractType: 'permanent' as ContractType,
    probationEndDate: new Date('2025-06-15'),
    emergencyContact: {
      name: 'Juan Garcia',
      relationship: 'Spouse',
      phone: '+1-555-0802',
    },
    createdAt: new Date('2024-12-15'),
    updatedAt: new Date('2024-12-15'),
  },
];

export function initializeMockData() {
  // Initialize localStorage with mock data if not already present
  if (!localStorage.getItem('employees')) {
    localStorage.setItem('employees', JSON.stringify(mockEmployees));
  }
  if (!localStorage.getItem('departments')) {
    localStorage.setItem('departments', JSON.stringify(mockDepartments));
  }
  if (!localStorage.getItem('roles')) {
    localStorage.setItem('roles', JSON.stringify(mockRoles));
  }
}

